export const ACTION_SET_LOADING = 'ACTION_SET_LOADING'
export const ACTION_SET_DATA = 'ACTION_SET_DATA'

export const IMPORT_FILE_REQUEST = 'IMPORT_FILE_REQUEST'
export const IMPORT_FILE_SUCCESS = 'IMPORT_FILE_SUCCESS'
export const IMPORT_FILE_ERROR = 'IMPORT_FILE_ERROR'

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'


export const CHANGE_SORT = 'CHANGE_SORT'
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const CHANGE_FILTER = 'CHANGE_FILTER'
export const RESET_FILTER = 'RESET_FILTER'

export const EDIT_CELL_REQUEST = 'EDIT_CELL_REQUEST'
export const EDIT_CELL_SUCCESS = 'EDIT_CELL_SUCCESS'
export const EDIT_CELL_ERROR = 'EDIT_CELL_ERROR'

export const REMOVE_ITEM_REQUEST = 'REMOVE_ITEM_REQUEST'
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS'
export const REMOVE_ITEM_ERROR = 'REMOVE_ITEM_ERROR'

export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR'

export const ADD_COLUMN_REQUEST = 'ADD_COLUMN_REQUEST'
export const ADD_COLUMN_SUCCESS = 'ADD_COLUMN_SUCCESS'
export const ADD_COLUMN_ERROR = 'ADD_COLUMN_ERROR'

export const CREATE_DOCUMENT_REQUEST = 'CREATE_DOCUMENT_REQUEST'
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS'
export const CREATE_DOCUMENT_ERROR = 'CREATE_DOCUMENT_ERROR'

export const RESET_HIGHLIGHTED_ITEM = 'RESET_HIGHLIGHTED_ITEM'

export const CHANGE_SHOWN_COLUMNS = 'CHANGE_SHOWN_COLUMNS'