export const ACTION_SET_LOADING = 'ACTION_SET_LOADING'
export const ACTION_SET_DATA = 'ACTION_SET_DATA'

export const IMPORT_FILE_REQUEST = 'IMPORT_FILE_REQUEST'
export const IMPORT_FILE_SUCCESS = 'IMPORT_FILE_SUCCESS'
export const IMPORT_FILE_ERROR = 'IMPORT_FILE_ERROR'

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'


export const CHANGE_SORT = 'CHANGE_SORT'
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const CHANGE_FILTER = 'CHANGE_FILTER'
export const RESET_FILTER = 'RESET_FILTER'