# Generated by Django 3.2.6 on 2021-09-08 19:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6871300e-5410-47d5-84fb-52a23ece1b0a'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('current_document', models.JSONField(null=True)),
            ],
        ),
    ]
