# Generated by Django 3.2.6 on 2021-09-08 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ynp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94fc5dbd-eae4-4c43-8a35-b8b1e315426b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
