# Generated by Django 3.2.6 on 2021-09-15 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ynp_app', '0005_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=2000)),
                ('priority', models.CharField(choices=[('1', 'Minor'), ('2', 'Medium'), ('3', 'High'), ('4', 'Critical'), ('5', 'Blocker')], max_length=2)),
                ('status', models.CharField(choices=[('1', 'Backlog'), ('2', 'To do'), ('3', 'In progress'), ('4', 'Testing'), ('5', 'Tested'), ('6', 'Reopen'), ('7', 'Done'), ('8', 'Frozen')], max_length=2)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignee', to='ynp_app.user')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_author', to='ynp_app.user')),
                ('related_tasks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ynp_app.task')),
            ],
        ),
    ]
