# Generated by Django 3.2.6 on 2021-09-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ynp_app', '0008_auto_20210915_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_author', to='ynp_app.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', 'Minor'), ('2', 'Medium'), ('3', 'High'), ('4', 'Critical'), ('5', 'Blocker')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Backlog'), ('2', 'To do'), ('3', 'In progress'), ('4', 'Testing'), ('5', 'Tested'), ('6', 'Reopen'), ('7', 'Done'), ('8', 'Frozen')], max_length=2, null=True),
        ),
    ]
