# Generated by Django 3.2.6 on 2021-09-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ynp_app', '0009_auto_20210915_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tag',
            new_name='tags',
        ),
    ]
