# Generated by Django 3.2.6 on 2021-09-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynp_app', '0010_rename_tag_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='ynp_app.Tag'),
        ),
    ]
