# Generated by Django 3.2.6 on 2021-09-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynp_app', '0014_auto_20210922_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
