# Generated by Django 3.2.6 on 2021-09-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynp_app', '0015_auto_20210922_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
