export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST'
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR'

export const CHANGE_FILTER = 'CHANGE_FILTER'
export const CHANGE_PAGINATION = 'CHANGE_PAGINATION'
export const RESET_FILTER = 'RESET_FILTER'

export const FETCH_DETAILS_REQUEST = 'FETCH_DETAILS_REQUEST'
export const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS'
export const FETCH_DETAILS_ERROR = 'FETCH_DETAILS_ERROR'

export const PATCH_DETAILS_REQUEST = 'PATCH_DETAILS_REQUEST'
export const PATCH_DETAILS_SUCCESS = 'PATCH_DETAILS_SUCCESS'
export const PATCH_DETAILS_ERROR = 'PATCH_DETAILS_ERROR'

export const RESET_DETAILS = 'RESET_DETAILS'

export const LOG_TIME_REQUEST = 'LOG_TIME_REQUEST'
export const LOG_TIME_SUCCESS = 'LOG_TIME_SUCCESS'
export const LOG_TIME_ERROR = 'LOG_TIME_ERROR'

export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR'

export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'

export const PATCH_PROFILE_REQUEST = 'PATCH_PROFILE_REQUEST'
export const PATCH_PROFILE_SUCCESS = 'PATCH_PROFILE_SUCCESS'

export const CHANGE_SORT = 'CHANGE_SORT'
